Description: >
  This template deploys a cluster of Filecoin nodes.

Parameters:
  EC2KeyName:
    Description: AWS key pair name for connecting to EC2 instances
    Type: AWS::EC2::KeyPair::KeyName
  LotusGitSHA:
    Description: Git SHA of lotus to build
    Type: String
  S3TemplateKeyPrefix:
    Description: An S3 key prefix which will be used to resolve referenced templates
    Type: String
  PeeredMinerScriptURL:
    Type: String
  GenesisMinerScriptURL:
    Type: String
  ConfigKeyPrefix:
    Description: Prefix of config keys
    Type: String
  ConfigBucketName:
    Description: Configuration bucket name
    Type: String

Resources:
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${S3TemplateKeyPrefix}security-groups.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt Network.Outputs.VPC
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${S3TemplateKeyPrefix}network.yml
      Parameters:
        AvailabilityZone:   !Select [ 0, !GetAZs ]
        EnvironmentName:    !Ref AWS::StackName
        VpcCIDR:            10.0.0.0/16
        PublicSubnet1CIDR:  10.0.10.0/26 # 64 addresses
  EC2InstanceGenesisMiner:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${S3TemplateKeyPrefix}ec2-instance-genesis-miner.yml
      Parameters:
        AvailabilityZone: !Select [ 0, !GetAZs ]
        EnvironmentName: !Ref AWS::StackName
        ConfigKeyPrefix: !Ref ConfigKeyPrefix
        ConfigBucketName: !Ref ConfigBucketName
        GenesisMinerScriptURL: !Ref GenesisMinerScriptURL
        KeyName: !Ref EC2KeyName
        LotusGitSHA: !Ref LotusGitSHA
        SecurityGroup: !GetAtt SecurityGroups.Outputs.EC2InstancesSecurityGroup
        Subnet: !GetAtt Network.Outputs.PublicSubnet1
        VPC: !GetAtt Network.Outputs.VPC
  EC2InstancePeeredMiner00:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${S3TemplateKeyPrefix}ec2-instance-peered-miner.yml
      Parameters:
        AvailabilityZone: !Select [ 0, !GetAZs ]
        EnvironmentName: !Ref AWS::StackName
        ConfigKeyPrefix: !Ref ConfigKeyPrefix
        ConfigBucketName: !Ref ConfigBucketName
        PeeredMinerScriptURL: !Ref PeeredMinerScriptURL
        KeyName: !Ref EC2KeyName
        LotusGitSHA: !Ref LotusGitSHA
        SecurityGroup: !GetAtt SecurityGroups.Outputs.EC2InstancesSecurityGroup
        Subnet: !GetAtt Network.Outputs.PublicSubnet1
        VPC: !GetAtt Network.Outputs.VPC

Outputs:
  EC2InstanceGenesisMiner:
    Value: !GetAtt EC2InstanceGenesisMiner.Outputs.EC2InstanceGenesisMinerIP
  EC2InstancePeeredMiner00:
    Value: !GetAtt EC2InstancePeeredMiner00.Outputs.EC2InstancePeeredMinerIP
