Description: >
  This template deploys a cluster of Filecoin nodes.

Parameters:
  EC2KeyName:
    Description: AWS key pair name for connecting to EC2 instances
    Type: AWS::EC2::KeyPair::KeyName
  LotusGitSHA:
    Description: Git SHA of lotus to build
    Type: String
  TemplateURLPrefix:
    Description: A prefix used to construct HTTP URLs from which we download CloudFormation templates (contains trailing slash)
    Type: String
  TemplateS3Prefix:
    Description: A prefix used to construct S3 URLs from which we construct AWS::Include snippets (contains trailing slash)
    Type: String
  PeeredMinerScriptURL:
    Type: String
  GenesisMinerScriptURL:
    Type: String
  ConfigKeyPrefix:
    Description: Prefix of config keys
    Type: String
  ConfigBucketName:
    Description: Configuration bucket name
    Type: String

Resources:
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateURLPrefix}security-groups.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt Network.Outputs.VPC
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateURLPrefix}network.yml
      Parameters:
        AvailabilityZone:   !Select [ 0, !GetAZs ]
        EnvironmentName:    !Ref AWS::StackName
        VpcCIDR:            10.0.0.0/16
        PublicSubnet1CIDR:  10.0.10.0/26 # 64 addresses
  EC2InstanceGenesisMiner:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-genesis-miner.yml
  EC2InstancePeeredMiner00:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner01:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner02:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner03:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner04:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner05:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner06:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner07:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner08:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner09:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner10:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner11:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner12:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner13:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner14:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner15:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner16:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner17:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner18:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml
  EC2InstancePeeredMiner19:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub ${TemplateS3Prefix}stack-peered-miner.yml

Outputs:
  GenesisBlock
  EC2InstanceGenesisMiner:
    Value: !GetAtt EC2InstanceGenesisMiner.Outputs.EC2InstanceGenesisMinerIP
  EC2InstancePeeredMinerIPs:
    Value: !Join
      - " "
      - - !GetAtt EC2InstancePeeredMiner00.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner01.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner02.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner03.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner04.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner05.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner06.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner07.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner08.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner09.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner10.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner11.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner12.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner13.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner14.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner15.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner16.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner17.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner18.Outputs.EC2InstancePeeredMinerIP
        - !GetAtt EC2InstancePeeredMiner19.Outputs.EC2InstancePeeredMinerIP
