Parameters:
  BucketName:
    Description: The name of the bucket used to store CloudFormation templates (will be publicly accessible)
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
